### ISSUE TITLE
Need Dataset

### ISSUE THREAD

**Issue by YLyouthful** [pykao/ISLES2017-mRS-prediction#1]
Hello

Since the original data of ISLES2017 cannot be downloaded now, may I ask if you can share the data? My email address is S2007048@st.nuc.edu.cn

Thank you!

**Comment by pykao** [comment]
Dear @YLyouthful ,

I do not have ISLES-2017 in my local workstation at this time. 

You are able to download the dataset in the following link:
https://www.smir.ch/ISLES/Start2017

Best,
PK
